name: Recreate staging branch

on:
  push:
    branches:
      - main

jobs:
  create_staging_branch:
    runs-on: ubuntu-latest

    steps:
    - name: Code checkout
      uses: actions/checkout@v4.1.1

    - name: Create staging branch from main
      run: |
        git checkout main
        git pull origin main
        git checkout -b staging
        git push origin staging
